### ISSUE TITLE
Page life cycle on Epiphany

### ISSUE THREAD

**Issue by davidhoness** [astro-pi/beta-testing#15] opened 2016-07-20 08:46 UTC
When I load the emulator using Epiphany on Raspbian the page load progress bar reaches 90% and stops for a long time. This is on a Pi 3. I'm not sure if it's having any adverse effects but thought I would raise it anyway.

**Comment by eah13** [comment] 2016-07-25 17:11
Dave, is this still happening to you?  I'm not able to reproduce but it reminds me of Epiphany's initial behavior before the recent fixes.  Epihany doesn't have hard refresh but I believe Settings > Personal Data > Clear Personal Data will clear cache.

**Comment by eah13** [comment] 2016-07-28 16:50
@davidhoness friendly ping.  Next time you test could you see if this is still happening?  Opening a private window is a good way to force a cache dump in case old code is cached.

**Comment by eah13** [comment] 2016-08-12 11:57
@davidhoness Closing this old one.  Feel free to reopen if you encounter again.

**Closed as completed by eah13** 2016-08-12 11:57 UTC
Labels: Trying to Reproduce
